[package]
name                    = "waf"
version                 =  "0.0.1"
description             =  "Rust Virtual Machine"
authors                 = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license                 =  "MIT"
repository              =  "https://github.com/ponyatov/waf"
edition                 =  "2024"

[dependencies]
const_format            = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
libc                    = "0.2"
memmap2                 = "0.9"

[[bin]]
name                    = "server"
path                    = "src/server.rs"

[features]
pc                      = ["i5"]
i5                      = ["x86_64"]
x86_64                  = ["linux"]
linux                   = []

