file(GLOB BINS
    ${CMAKE_INSTALL_PREFIX}/${BIN_OUTPUT_NAME}*
        ${CMAKE_BINARY_DIR}/${BIN_OUTPUT_NAME}*)

set_property (
    TARGET ${CMAKE_PROJECT_NAME}
    APPEND PROPERTY ADDITIONAL_CLEAN_FILES ${BINS} ${ELF} ${DFU})
